[package]
name = "app"
version = "1.0.0"
description = "A simple desktop application template combining Tauri 2 with Svelte 5 and shadcn-svelte with a basic ci/cd implemented."
authors = ["Alysonhower Veras Vieira"]
license = "MIT"
repository = "alysonhower/tauri2-svelte5-shadcn"
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.2.0", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.6.2", features = ["protocol-asset"] }
tauri-plugin-log = "2"
tauri-plugin-dialog = "2.4"
thiserror = "2.0.12"
base64 = "0.22"
image = { version = "0.25", features = ["png", "jpeg", "webp", "avif", "avif-native", "gif", "bmp", "ico", "tiff", "tga"] }
jxl-oxide = { version = "0.12.2", features = ["image"] }
zip = "6.0.0"
walkdir = "2.5"
threadpool = "1.8"
rusqlite = { version = "0.32.0", features = ["bundled"] }
chrono = { version = "0.4", features = ["serde"] }
url = "2.5"
md5 = "0.7.0"
pyo3 = { version = "0.21", features = ["auto-initialize"] }
numpy = "0.21"
